name: Cron

on:
  schedule:
    - cron: "0 2 * * *"
    # Assume that run at UTC+8 10:00
    # Convert To UTC -> 10:00 - 8:00 = 2:00

jobs:
  Cron:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.3"
      - run: go run bot.go
        env:
          Token: ${{ secrets.Token }}
          Chat_ID: ${{ secrets.Chat_ID}}
