name: Cron

on: 
  schedule:
  - cron: "0 8 * * *"

jobs:
  Cron:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: "^1.16.3"
      - run: go run bot.go
        env:
            Token: ${{ secrets.Token }}
            Chat_ID: ${{ secrets.Chat_ID}}
