name: Test

on: workflow_dispatch 

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with: 
          go-version: "^1.13.1"
      - run: go run bot.go
        env:
            Token: ${{ secrets.Token }}
            Chat_ID: ${{ secrets.Chat_ID}}
